version: '3.8'

services:
  # container_name: rag_postgres
  db:
    image: pgvector/pgvector:pg15
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./startup_sql.sql:/docker-entrypoint-initdb.d/pgvector-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./apps/api
      dockerfile: ../../Dockerfile.api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  
    volumes: 
      - ./apps:/app
      - ./apps/shared:/app/api/shared
      - ./apps/Model:/app/model

  redis:
    image: redis:7
    container_name: rag_redis
    ports:
      - "6379:6379"
  
  worker:
    build:
      context: ./apps/worker
      dockerfile: ../../Dockerfile.worker
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./apps:/app
      - ./apps/shared:/app/worker/shared
      - ./apps/Model:/app/model
volumes:
  postgres_data: {}

  
